name: Action Release
on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*-*"
  merge_group:
    branches:
      - main
  release:
    types:
      - created
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build project assets
        id: checkout
        run: |
          mkdir -pv Jnvim
          cp -rv init.lua assets lua queries README.md LICENSE Jnvim
          tar cvJf Jnvim.tar.xz Jnvim
          tar cvzf Jnvim.tar.gz Jnvim
          zip -r -9 Jnvim.zip Jnvim
          7z a -mx9 -mmt -sdel Jnvim.7z Jnvim
          sha512sum Jnvim.7z Jnvim.zip Jnvim.tar.xz Jnvim.tar.gz >| sha512sums.txt
          md5sum Jnvim.7z Jnvim.zip Jnvim.tar.xz Jnvim.tar.gz >| md5sums.txt
      - name: Get Release
        id: get_current_release
        uses: joutvhu/get-release@v1.0.3
        with:
          latest: true
          prerelease: true
          pattern: '^v.*'
          debug: true
          throwing: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Release File
        run: |
          echo ${{ github.sha }} >| Release.txt
          cat Release.txt
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            Release.txt
            md5sums.txt
            sha512sums.txt
            Jnvim.7z
            Jnvim.tar.gz
            Jnvim.tar.xz
            Jnvim.zip
          token: ${{ secrets.GITHUB_TOKEN }}
# vim: set ts=2 sts=2 sw=2 et ai si sta:
